### ISSUE TITLE
select_console 'root-console' has troubles matching after restoring a snapshot

### ISSUE THREAD

**Issue by hwoarang** [os-autoinst/os-autoinst#531] opened 2016-07-06 15:58 UTC
Hi,

Here is a log of my local openQA instance which makes use of snapshots to go straight to the ```console/dns_srv``` test

```
15:32:51.9081 skipping console-mysql_srv
15:32:51.9084 Loading a VM snapshot console-dns_srv
15:33:16.6322 EVENT {"timestamp":{"microseconds":909587,"seconds":1467819171},"event":"STOP"}
15:33:16.6324 EVENT {"timestamp":{"seconds":1467819196,"microseconds":630204},"event":"RESUME"}
15:33:16.6449 EVENT {"timestamp":{"seconds":1467819196,"microseconds":644668},"event":"STOP"}
15:33:16.6464 EVENT {"timestamp":{"seconds":1467819196,"microseconds":646172},"event":"RESUME"}
15:33:26.6472 pointer type 1 0 640 480 -257
15:33:26.6507 ||| starting dns_srv tests/console/dns_srv.pm at 2016-07-06 15:33:26
15:33:26.7271 Debug: /var/lib/openqa/share/tests/opensuse/tests/console/dns_srv.pm:17 called testapi::select_console
15:33:26.7273 <<< testapi::select_console(testapi_console='root-console')
15:33:27.0001 Debug: /var/lib/openqa/share/tests/opensuse/tests/console/dns_srv.pm:17 called testapi::select_console
15:33:27.0003 <<< testapi::assert_screen(mustmatch='tty2-selected', timeout=60)
15:33:27.1694 MATCH(tty2-selected-20151130:0.00)
15:33:27.1696 no match 60
15:33:28.0299 MATCH(tty2-selected-20151130:0.00)
15:33:28.0300 no match 58
15:33:29.0296 MATCH(tty2-selected-20151130:0.00)
15:33:29.0297 no match 57
15:33:30.0023 no change 56
15:33:31.1169 MATCH(tty2-selected-20151130:0.00)
...
15:34:26.1399 no match 0
15:34:27.1626 MATCH(tty2-selected-20151130:0.00)
15:34:27.1633 >>> testapi::_check_or_assert: match=tty2-selected timed out after 60
test dns_srv failed at /usr/lib/os-autoinst/basetest.pm line 293.
15:34:27.3108 test dns_srv failed
...
15:35:19.5712 ||| starting docker tests/console/docker.pm at 2016-07-06 15:35:19
15:35:19.5718 Debug: /var/lib/openqa/share/tests/opensuse/tests/console/docker.pm:16 called testapi::select_console
15:35:19.5719 <<< testapi::select_console(testapi_console='root-console')
15:35:19.8227 Debug: /var/lib/openqa/share/tests/opensuse/tests/console/docker.pm:19 called testapi::assert_script_run
```

As you can see, for whatever reason, the ```select_console 'root-console'``` does not seem to match upon snapshot restoration so the test fails. The strange thing is that the subsequent tests work fine.

When the snapshot is restored, the VM console looks like this

![openqa_restore_vm](https://cloud.githubusercontent.com/assets/45309/16624981/ba4bdaea-439a-11e6-90e8-bba45cfde675.png)

**Comment by okurz** [comment] 2016-07-06 16:06
thank you for reporting. This is a duplicate of https://progress.opensuse.org/issues/10484 *"select_console 'root-console'" in tests breaks continuation from snapshots*

**Comment by hwoarang** [comment] 2016-07-06 17:41
oops sorry my bad for not checking the other place before I report it here.

**Comment by coolo** [comment] 2016-07-10 12:32
no problem, but please understand that there is no value in keeping the dup

**Closed by coolo** 2016-07-10 12:32 UTC
